### ISSUE TITLE
KVM is not working well

### ISSUE THREAD

**Issue by koraniar** [jsastriawan/mps-microservice#12]
Since a few days ago we are experiencing some troubles trying to connect us to KVM, when we turn on the server it always allows connections through CIRA and we can send actions to the computer like turn on, restart, shutdown, etc.  But some times when we try to connect us to KVM the server returns an error that don't let us connect, and after restart the server the KVM connection works well.
What do you think that can cause this behavior?
What do you recommend us review to resolve this problem?

**Comment by ricardopolo** [comment]
To clarify: all actions stops working correctly, but KVM does not. 
We use “Relay” for KVM. We use the API methods to all other actions.

**Comment by jsastriawan** [comment]
There are things Ylian fixed on his mpsserver.js. I will look at this and apply the changes. It seems channel creation issue.

As a temporary workaround for the moment, I added disconnect call to cut CIRA connection so that AMT client could re-establish connection while I am working on the issue.

**Comment by ricardopolo** [comment]
@jsastriawan thanks for your fast answer. Did you commit that conga already or are planning to do in the next days?
If you did we will update our Fork and try again in production!! 
We are already testing this MPS micro service with several machines in production 👍

**Comment by jsastriawan** [comment]
See webserver.js for GET disconnect.ashx. It is just as simple as calling socket.end() :smiley:

I am very happy to hear that it is working for you. Let us know when you need marketing side to help.

**Comment by jsastriawan** [comment]
I just posted few fixes on mpsserver.js where certain failures could result wrong pointer returned for next command parsing. Please test.

**Comment by ricardopolo** [comment]
We updated our fork with all your latest code, and put in production. We'll be monitoring and see if the random disconnects continue happening. 

@koraniar please close this issue and only reopen it if we continue seeing this disconnections.

In the next few days we will capture logs and exceptions from our running MPS micro service and send it to our [Sentry](https://sentry.io/tulpep/) instance. After a few days of monitoring the logs if we found there are some unmanaged exceptions we will report it to you.

Ps. I will contact you soon for talk about marketing, thanks for the offering 😄
